# Generated by Django 3.2.9 on 2021-12-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='date',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
